export const PARAMETER_HELP = Object.freeze({
  common: Object.freeze({
    tag: '点位在 DataCenter、协议模块和控制配置之间使用的标识。同一连接内应保持唯一，其他配置通常通过该名称引用点位。',
    dataType: '决定原始数据的解析方式和可用配置项。必须与设备协议文档中的数据类型一致。',
    scale: '工程量 = 原始值 × 缩放系数 + 偏移量。缩放系数填 0 时按 1 处理。',
    offset: '工程量 = 原始值 × 缩放系数 + 偏移量。偏移量与最终工程量单位相同。',
    deadband: '仅当工程量变化达到该值时上报；填 0 或负数表示不进行变化过滤。',
    pollInterval: '相邻轮询周期的时间间隔。数值越小更新越及时，但会增加通信负载和设备压力。',
    requestTimeout: '发出请求后等待完整响应的最长时间。过小可能把慢响应误判为超时，过大会延长故障恢复时间。',
    connectTimeout: '建立网络连接时允许等待的最长时间。过小可能在网络抖动时连接失败。',
    serialPort: '串口链路的设备路径或远端 uartManager 端口标识，必须与实际接线和端口配置一致。',
    baudRate: '串口每秒传输的符号数，必须与现场设备设置一致。',
    dataBits: '每个串口字符包含的数据位数，必须与现场设备设置一致。',
    parity: '串口字符的奇偶校验方式，必须与现场设备设置一致。',
    stopBits: '每个串口字符末尾的停止位数量，必须与现场设备设置一致。',
    serialByteTimeout: '接收一帧数据时，等待下一个字节的最长时间。填 0 时使用模块默认值。',
    serialFrameTimeout: '从开始接收起等待整帧完成的最长时间。填 0 时使用模块默认值。',
    serialEstimatedSize: '预估单次响应的最大接收字节数，用于串口透传接收和缓冲区规划。',
  }),
  modbus: Object.freeze({
    transportType: '本地串口直接访问设备；MQTT 透传则通过 MQTTManager 和远端 uartManager 访问串口。',
    deviceId: 'Modbus RTU 从站地址，有效范围为 1～247，必须与设备地址一致。',
    unitId: 'Modbus TCP 报文中的单元标识，常用于网关后区分不同 RTU 从站，范围为 1～247。',
    host: 'Modbus TCP 设备或网关的 IP 地址或域名。',
    addressBase: '0 基表示填写协议报文中的实际偏移地址；1 基表示填写设备文档中的人类编号，例如 40001。',
    functionCode: '决定读取或写入的 Modbus 数据区。功能码必须与设备点表中的寄存器类型一致。',
    address: '点位的 Modbus 地址，解释方式由连接配置中的“地址基准”决定。',
    registerCount: '该点连续占用的 16 位寄存器数量，通常由数据类型决定。',
    bitIndex: '从寄存器中提取 BOOL 值时使用的位序号，0 表示最低有效位。',
    wordOrder: '32 位数据跨两个寄存器时的排列顺序：HL 为高字在前，LH 为低字在前。',
    byteOrder: '每个 16 位寄存器内部的字节顺序：AB 为高字节在前，BA 为低字节在前。',
  }),
  dlt645: Object.freeze({
    protocolVariant: '标准版按 DLT645 表计协议通信；PCD 版通过协议转换器通信，并需要额外配置设备序号。',
    meterAddress: '12 位表计地址；在 PCD 模式下表示协议转换器地址。',
    deviceNumber: 'PCD 模式下用于区分转换器后的设备，填写两位十六进制字符串，例如 0A。',
    communicationMode: '选择现场实际使用的载波、串口或 LoRa 通信通道。',
    pollItemInterval: '一次点抄收发完成后，到下一次点抄开始前的额外等待时间；填 0 表示不额外等待。',
    dataIdentifier: 'DLT645 的 4 字节数据标识，界面按高字节在前填写 8 位十六进制字符串，例如 02010100。',
    blockDataIdentifier: '一个 DI 对应多个连续子项时使用的数据块标识，填写规则与普通 DI 相同。',
    dataLength: '响应数据域占用的字节数，不包含 DI 和 PCD 设备序号。',
    access: '限制该点位可执行的操作。只读点不能下发写命令，只写点不参与轮询读取。',
    byteIndex: 'BOOL 位解析所在的字节序号，0 表示数据域的第一个字节。',
    bitIndex: 'BOOL 位解析所在的位序号，0 表示当前字节的最低有效位。',
    trimRightSpace: '开启后会移除 ASCII 字符串右侧的填充空格；关闭时保留原始空格。',
  }),
  iec104: Object.freeze({
    transportRole: 'SERVER 在本地监听连接；CLIENT 主动连接远端。该选项只决定 TCP 连接方向。',
    stationRole: '主站负责发起控制和对时，从站负责上送点值并响应命令；它决定 IEC104 业务语义。',
    commonAddress: 'IEC104 ASDU 的公共地址，用于标识站点，通信双方必须配置一致。',
    originatorAddress: 'IEC104 命令的源发地址，通常使用 0；如现场规约有明确要求，请按对端配置填写。',
    timeSyncTag: '主站订阅该 DataCenter 标签，标签更新时发送时钟同步命令；留空时使用 __time_sync__。',
    localIp: 'SERVER 模式下为监听地址；CLIENT 模式下为可选的本地绑定地址，留空由系统选择。',
    remoteIp: 'CLIENT 模式下要连接的远端 IEC104 地址。',
    allowedMasterIps: 'SERVER 模式下允许接入的主站 IP；留空、0.0.0.0 或 :: 表示不限制来源。',
    port: 'IEC104 TCP 端口，标准端口通常为 2404；必须与对端配置一致。',
    apciK: '尚未确认的已发送 I 帧最大数量，即发送窗口大小。双方参数应协调配置。',
    apciW: '收到多少个 I 帧后发送确认，即接收确认窗口大小；通常应小于 k。',
    apciT0: '建立 TCP 连接允许的最长时间，单位秒。',
    apciT1: '发送 I 帧或测试帧后等待确认的最长时间，单位秒。',
    apciT2: '未达到 w 个 I 帧时，延迟发送确认的最长时间，单位秒。',
    apciT3: '链路空闲后发送测试帧的等待时间，单位秒。',
    batchWindow: '自发点值在该时间窗口内合并发送。窗口越大报文更少，但数据延迟会增加；填 0 使用默认值。',
    maxAsduBytes: '点值 ASDU 单帧允许的最大字节数；开启“标准限值”后固定使用 IEC104 标准的 249 字节上限。',
    standardLimit: '开启后强制使用 IEC104 标准的 249 字节上限，并忽略自定义最大 ASDU 字节数。',
    withTimestamp: '开启后点值使用带时标类型上送；对端必须支持对应的 CP56Time2a 时标类型。',
    deduplicate: '开启后，同一合包窗口内相同 IOA 只保留最后一次更新；关闭后保留全部更新。',
    ioaCategory: '按遥信、遥测、遥调等业务类别管理 IOA 范围，便于自动分配和发现地址冲突。',
    ioa: 'IEC104 信息体地址，同一连接内必须唯一，并应符合现场点表规划。',
    pointType: '决定 IEC104 协议数据类型：FLOAT 用于短浮点量，SINGLE 用于单点状态。',
    businessType: '描述点位的业务用途，例如遥测、遥信、遥调或遥控，并决定可用的命令配置。',
    remoteControlType: '单点遥控使用 C_SC_NA_1，双点遥控使用 C_DC_NA_1；仅遥控业务生效。',
    commandExecutionMode: '直接执行会立即发送执行命令；选择执行会先选择、确认后再执行。仅遥控业务生效。',
  }),
  mqtt: Object.freeze({
    host: 'MQTT Broker 的 IP 地址或域名，供协议模块建立透传连接。',
    port: 'MQTT Broker 的服务端口，默认通常为 1883；如启用 TLS 或使用现场网关，请按 Broker 配置填写。',
    clientId: 'MQTT 客户端的唯一标识。同一 Broker 上重复使用可能导致已有连接被踢下线。',
    keepalive: '客户端与 Broker 之间的保活周期，单位秒；应小于网络设备的空闲连接回收时间。',
    cleanSession: '开启后每次连接使用新会话，不恢复 Broker 保存的旧会话状态；关闭后可恢复持久会话。',
  }),
  control: Object.freeze({
    avcCommandMode: '目标电压模式根据电压偏差计算总无功目标；总无功模式直接接收总无功命令进行成员分配。',
    controlMode: 'PI 事件触发会在相关输入点更新时计算；周期直分配按固定周期重新计算并下发目标。',
    allocationMode: '平均分配使用相同权重；比例分配按容量或可调范围计算；自定义模式使用成员的调节权重。',
    calculationPeriod: '周期直分配模式下重新读取测量值并计算分配结果的周期，范围为 1～15 秒。',
    commandPeriod: '周期直分配模式下向成员下发控制命令的周期，范围为 4～30 秒。',
    signalTag: '控制模块通过该 DataCenter 标签接收测量或命令，也通过标签发布派生结果。',
    unit: '该信号换算后的工程量单位，应与现场含义及控制组中的其他相关信号保持一致。',
    commandMode: '绝对值模式直接使用输入值；增量值模式把输入值叠加到所选基准后生成目标。',
    deltaBase: '增量值模式的计算基准，可选择上一轮目标值、当前实测值或指定 base_tag 的值。',
    baseTag: '增量值模式使用的外部基准点标签，仅在“指定 base_tag”时生效。',
    controllable: '关闭后该成员仍可参与测量汇总，但不会参与控制量分配或接收设定命令。',
    capacity: '成员的额定有功容量，用于容量比例分配和成员参数边界校验。',
    weight: '自定义分配模式下的相对权重；系统会对所有可控成员的权重归一化。',
    activeLimits: '成员允许接收的有功目标边界；达到边界后，剩余控制量会重新分配给其他可控成员。',
    reactiveLimits: '成员允许接收的无功目标边界；达到边界后，剩余控制量会重新分配给其他可控成员。',
    voltageKp: '电压偏差超出死区后，按 q = q_meas + kp × (v_ref - v_meas) 计算期望总无功。',
    voltageDeadband: '当电压偏差绝对值不超过该值时，不再继续推动总无功目标变化。',
  }),
});
