import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import assert from 'node:assert/strict';

const repoRoot = path.resolve(import.meta.dirname, '..', '..');

// 验证纵密配置入口、路由和页面组件保持一致。
test('纵密配置可以从侧边栏切换到独立页面', () => {
  const layoutText = fs.readFileSync(path.join(repoRoot, 'src/layouts/MainLayout.tsx'), 'utf8');
  const routeText = fs.readFileSync(path.join(repoRoot, 'src/router.tsx'), 'utf8');
  const routeComponentsText = fs.readFileSync(path.join(repoRoot, 'src/route-components.tsx'), 'utf8');
  const pageText = fs.readFileSync(path.join(repoRoot, 'src/pages/SecurityConfig/index.tsx'), 'utf8');
  const scriptText = fs.readFileSync(path.join(repoRoot, 'src/utils/vertical-security-script.ts'), 'utf8');
  const adapterTypesText = fs.readFileSync(path.join(repoRoot, 'src/adapters/types.ts'), 'utf8');
  const tauriAdapterText = fs.readFileSync(path.join(repoRoot, 'src/adapters/tauri.ts'), 'utf8');
  const browserAdapterText = fs.readFileSync(path.join(repoRoot, 'src/adapters/browser.ts'), 'utf8');
  const rustCommandText = fs.readFileSync(path.join(repoRoot, 'src-tauri/src/commands/lower_update.rs'), 'utf8');
  const rustLibText = fs.readFileSync(path.join(repoRoot, 'src-tauri/src/lib.rs'), 'utf8');

  assert.match(layoutText, /key: '\/security-config'/);
  assert.match(layoutText, /label: '纵密配置'/);
  assert.match(routeComponentsText, /SecurityConfigPage = lazy\(\(\) => import\('\.\/pages\/SecurityConfig'\)\)/);
  assert.match(routeText, /path: 'security-config'/);
  assert.match(routeText, /<SecurityConfigPage \/>/);
  assert.match(pageText, /<Card title="纵密配置"/);
  assert.match(pageText, /电脑需使用 11\.22\.33\.0\/24 网段内的地址访问 11\.22\.33\.44/);
  assert.match(pageText, /不属于 RTU、网关或纵密配置字段/);
  assert.match(pageText, /label="目标设备"/);
  assert.match(pageText, /value: 'MskDSP', label: 'MskDSP'/);
  assert.match(pageText, /uploadAccount: 'megsky@192\.168\.1\.219:10022'/);
  assert.match(pageText, /sshPassword: 'Meg@admin123'/);
  assert.match(pageText, /onChange=\{handleDeviceChange\}/);
  assert.match(pageText, /disabled=\{!selectedDevice\}/);
  assert.match(pageText, /label="本地 RTU 地址"/);
  assert.match(pageText, /isValidIpv4Address/);
  assert.match(pageText, /请输入合法 IPv4 地址/);
  assert.match(pageText, /label="本地纵密地址"/);
  assert.match(pageText, /label="本地网关地址"/);
  assert.match(pageText, /label="远程 RTU 地址"/);
  assert.match(pageText, /label="远程纵密地址"/);
  assert.match(pageText, /label="远程网关地址"/);
  assert.match(pageText, />\s*执行\s*<\/Button>/);
  assert.match(pageText, /buildVerticalSecurityScript/);
  assert.match(pageText, />\s*查看脚本\s*<\/Button>/);
  assert.match(pageText, /title="纵密配置脚本预览"/);
  assert.match(pageText, /启动请求已提交/);
  assert.match(pageText, /deployVerticalSecurityScript/);
  assert.match(pageText, /api\.getVerticalSecurityStatus/);
  assert.match(pageText, /STATUS_POLL_INTERVAL_MS = 2000/);
  assert.match(pageText, /setTimeout\(poll, STATUS_POLL_INTERVAL_MS\)/);
  assert.match(pageText, /执行流程/);
  assert.match(pageText, /label: '等待中'/);
  assert.match(pageText, /label: '失败'/);
  assert.match(pageText, /纵密配置全部步骤执行完成/);
  assert.match(pageText, /下发纵密配置失败/);
  assert.match(adapterTypesText, /export interface VerticalSecurityDeployRequest/);
  assert.match(adapterTypesText, /export interface VerticalSecurityDeployResult/);
  assert.match(adapterTypesText, /export interface VerticalSecurityStatusRequest/);
  assert.match(adapterTypesText, /export interface VerticalSecurityStatusResult/);
  assert.match(adapterTypesText, /export type VerticalSecurityStepState = 'running' \| 'waiting' \| 'success' \| 'failed'/);
  assert.match(tauriAdapterText, /deploy_vertical_security_script/);
  assert.match(tauriAdapterText, /get_vertical_security_status/);
  assert.match(browserAdapterText, /浏览器开发模式已模拟脚本上传、服务安装和启动/);
  assert.match(browserAdapterText, /getVerticalSecurityStatus/);
  assert.match(rustLibText, /commands::lower_update::deploy_vertical_security_script/);
  assert.match(rustLibText, /commands::lower_update::get_vertical_security_status/);
  assert.match(rustCommandText, /pub async fn deploy_vertical_security_script/);
  assert.match(rustCommandText, /pub async fn get_vertical_security_status/);
  assert.match(rustCommandText, /__MSKDSP_STEPS_BEGIN__/);
  assert.match(rustCommandText, /\/run\/mskdsp-vertical-security\/steps\.log/);
  assert.match(rustCommandText, /parse_vertical_security_status_output/);
  assert.match(rustCommandText, /bash -n \{script_path\}/);
  assert.match(rustCommandText, /Description=MskDSP 纵密配置/);
  assert.match(rustCommandText, /StartLimitIntervalSec=0/);
  assert.match(rustCommandText, /Type=exec/);
  assert.doesNotMatch(rustCommandText, /Type=oneshot/);
  assert.match(rustCommandText, /TimeoutStartSec=30s/);
  assert.match(rustCommandText, /Restart=on-failure/);
  assert.match(rustCommandText, /RestartSec=10s/);
  assert.match(rustCommandText, /systemctl cat \{service_name\}/);
  assert.match(rustCommandText, /systemctl daemon-reload/);
  assert.match(rustCommandText, /systemctl enable/);
  assert.match(rustCommandText, /systemctl is-enabled --quiet/);
  assert.match(rustCommandText, /systemctl restart --no-block/);
  assert.match(rustCommandText, /rm -f -- \/run\/mskdsp-vertical-security\/steps\.log/);
  assert.match(rustCommandText, /systemctl show --property=ActiveState --value/);
  assert.match(scriptText, /sysctl -w net\.ipv4\.ip_forward=1/);
  assert.match(scriptText, /ip addr replace 11\.22\.33\.1\/32 dev eth0\.101/);
  assert.match(scriptText, /ip route del 11\.22\.33\.41\/32 dev eth0\.101/);
  assert.match(scriptText, /ip route replace 11\.22\.33\.0\/24 dev eth0\.101 scope link/);
  assert.doesNotMatch(scriptText, /ip route replace 11\.22\.33\.41\/32/);
  assert.match(scriptText, /ip route replace 11\.22\.33\.44\/32 dev eth0\.108 scope link/);
  assert.match(scriptText, /ip addr replace "\\\$\{LOCAL_GATEWAY_ADDRESS\}\/32" dev eth0\.107/);
  assert.match(scriptText, /ip route replace "\\\$\{LOCAL_SECURITY_ADDRESS\}\/32" dev eth0\.107 scope link src "\\\$\{LOCAL_GATEWAY_ADDRESS\}"/);
  assert.match(scriptText, /ip addr replace "\\\$\{LOCAL_RTU_ADDRESS\}\/32" dev eth0\.108/);
  assert.match(scriptText, /ip route replace "\\\$\{REMOTE_RTU_ADDRESS\}\/32" via 192\.168\.8\.220 dev eth0\.108 src "\\\$\{LOCAL_RTU_ADDRESS\}"/);
  assert.match(scriptText, /src "\\\$\{LOCAL_RTU_ADDRESS\}" onlink/);
  assert.match(scriptText, /ip route replace "\\\$\{REMOTE_SECURITY_ADDRESS\}\/32" dev ppp0/);
  assert.match(scriptText, /wait_for_ppp0_ipv4/);
  assert.match(scriptText, /export function isValidIpv4Address/);
  assert.match(scriptText, /requireIpv4Address/);
  assert.match(scriptText, /必须是合法 IPv4 地址/);
  assert.match(scriptText, /readonly STATUS_LOG="\\\$\{STATUS_DIR\}\/steps\.log"/);
  assert.match(scriptText, /begin_step 'ppp0_wait' 'PPP 链路'/);
  assert.match(scriptText, /write_step_status 'waiting' '等待 ppp0 IPv4 地址'/);
  assert.match(scriptText, /begin_step 'save_config' '配置保存'/);
  assert.match(scriptText, /local interval_seconds=5/);
  assert.match(scriptText, /while true/);
  assert.match(scriptText, /iptables -t nat -I PREROUTING 1 -i ppp0/);
  assert.match(scriptText, /remove_managed_dnat_rule/);
  assert.match(scriptText, /--to-destination "\\\$\{LOCAL_SECURITY_ADDRESS\}"/);
  assert.doesNotMatch(scriptText, /-m comment|DNAT_COMMENT/);
  assert.match(scriptText, /net\.netfilter\.nf_conntrack_generic_timeout=3/);
  assert.match(scriptText, /sleep 30/);
  assert.match(scriptText, /net\.netfilter\.nf_conntrack_generic_timeout=600/);
  assert.match(scriptText, /iptables -t nat -D POSTROUTING -o eth0\.108 -s 11\.22\.33\.41\/32 -d 11\.22\.33\.44\/32 -j SNAT --to-source 11\.22\.33\.2/);
  assert.match(scriptText, /iptables -t nat -C POSTROUTING -o eth0\.108 -s 11\.22\.33\.0\/24 -d 11\.22\.33\.44\/32 -j SNAT --to-source 11\.22\.33\.2/);
  assert.doesNotMatch(scriptText, /iptables -t nat -A POSTROUTING .* -s 11\.22\.33\.41\/32/);
  assert.match(scriptText, /LOCAL_RTU_ADDRESS=\\\$\{LOCAL_RTU_ADDRESS\}/);
  assert.match(scriptText, /REMOTE_GATEWAY_ADDRESS=\\\$\{REMOTE_GATEWAY_ADDRESS\}/);
});
