export type {
  AppUpdateDownloadEvent,
  AppUpdateInfo,
  AppUpdateStatus,
  AppUpdateStatusKind,
  AppSettingsMap,
  CacheClearResult,
  LowerUpdateChannel,
  LowerUpdateCachedPackage,
  LowerUpdateDownloadProgress,
  LowerUpdateDownloadResult,
  LowerUpdateDownloadStage,
  LowerUpdateInstallRequest,
  LowerUpdateInstallResult,
  LowerUpdateManifest,
  LowerUpdateRuntimeInfo,
  LowerUpdateRuntimeInfoRequest,
  LowerUpdateSshAuth,
  LowerUpdateUploadProgress,
  LowerUpdateUploadRequest,
  LowerUpdateUploadResult,
  LowerUpdateUploadStage,
  VerticalSecurityDeployRequest,
  VerticalSecurityDeployResult,
  VerticalSecurityStatusRequest,
  VerticalSecurityStatusResult,
  VerticalSecurityStepResult,
  VerticalSecurityStepState,
  ModuleDependency,
  ModuleInfo,
  ModuleRunningInfo,
  ModuleVersion,
  RuntimeDirectoryKind,
  RuntimePaths,
} from './types';
export type {
  Iec104ApciParameters,
  Iec104Endpoint,
  Iec104LinkConfig,
  Iec104LinkInfo,
  Iec104Point,
  Iec104PointTable,
  Iec104SimulationPoint,
  Iec104SimulationSnapshot,
  Iec104SimulationGenerateOptions,
  Iec104SimulationMode,
  Iec104SimulationBoolMode,
} from './types';
export type {
  Iec61850ChannelInfo,
  Iec61850IedConfig,
  Iec61850IedInfo,
  Iec61850ImportResult,
  Iec61850ModelSummary,
  Iec61850NetworkChannelConfig,
  Iec61850PointMapping,
  Iec61850PointMappings,
  Iec61850ProtectionRule,
  Iec61850RuntimeStatistics,
  Iec61850ValidationIssue,
} from './types';
export type {
  ModbusLinkConfig,
  ModbusLinkInfo,
  ModbusMqttConfig,
  ModbusPoint,
  ModbusPointTable,
  ModbusReadBlock,
  ModbusReadPlan,
  ModbusSerialConfig,
  ModbusUpdateConfigResponse,
} from './types';
export type {
  Dlt645Block,
  Dlt645BlockItem,
  Dlt645LinkConfig,
  Dlt645LinkInfo,
  Dlt645MqttConfig,
  Dlt645Point,
  Dlt645PointTable,
  Dlt645UpdateConfigResponse,
} from './types';
export type {
  DcConnTags,
  DcConnectionInfo,
  DcEndpoint,
  DcPointUpdate,
  DcSourcePointUpdate,
  DcPointValue,
  DcRoute,
  DataBusThroughputSample,
  DataBusThroughputSnapshot,
  DataBusThroughputSource,
  ControlOrchestratorCommandStep,
  ControlOrchestratorWorkflowConfig,
  ControlOrchestratorExecuteRequest,
  ControlOrchestratorExecuteResponse,
} from './types';
export type {
  CalcGroupConfig,
  CalcGroupInfo,
  CalcItemConfig,
  CalcItemInfo,
  CalcOperandStatus,
  CalcOperandSpec,
  CalcTypedConstant,
} from './types';
export type {
  AgcDefaultPointInfo,
  AgcControlProfile,
  AgcMemberControlProfile,
  AgcTuningConfig,
  AgcTuningStatus,
  AvcDefaultPointInfo,
  AvcGroupConfig,
  AvcGroupInfo,
  AvcMemberConfig,
  AvcSignalSpec,
  AvcStrategyConfig,
  AvcValueSpec,
  AvcVoltageControlConfig,
  ConfigExportMetadata,
  ConfigExportSectionId,
  AgcDerivedOutputs,
  AgcExportTask,
  AgcGroupConfig,
  AgcGroupInfo,
  AgcMemberConfig,
  AgcSignalSpec,
  AgcStrategyConfig,
  AgcValueSpec,
  Dlt645ExportTask,
  FullConfigExportSnapshot,
  Iec104ExportTask,
  ModbusRtuExportTask,
  StableDataBusEndpoint,
  StableDataBusRoute,
} from './types';
import { browserApi } from './browser';
import { api as tauriApi } from './tauri';

function hasTauriRuntime() {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

export const api: typeof tauriApi = hasTauriRuntime() ? tauriApi : browserApi;
